"""Initial database

Revision ID: a0c15eb956c2
Revises: 
Create Date: 2026-07-19 17:44:18.956788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0c15eb956c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculties',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('faculties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faculties_code'), ['code'], unique=True)

    op.create_table('job_sources',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('organisation', sa.String(length=100), nullable=True),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('regions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regions_name'), ['name'], unique=True)

    op.create_table('school_types',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('school_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_types_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_school_types_name'), ['name'], unique=True)

    op.create_table('localities',
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('postcode', sa.String(length=10), nullable=True),
    sa.Column('lga', sa.String(length=100), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'postcode', name='uq_locality_name_postcode')
    )
    with op.batch_alter_table('localities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_localities_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_localities_region_id'), ['region_id'], unique=False)

    op.create_table('subjects',
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subjects_code'), ['code'], unique=True)

    op.create_table('schools',
    sa.Column('locality_id', sa.Integer(), nullable=False),
    sa.Column('school_type_id', sa.Integer(), nullable=False),
    sa.Column('acara_id', sa.Integer(), nullable=True),
    sa.Column('school_code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('short_name', sa.String(length=80), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('town_suburb', sa.String(length=100), nullable=True),
    sa.Column('postcode', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('remoteness', sa.Enum('MAJOR_CITIES', 'INNER_REGIONAL', 'OUTER_REGIONAL', 'REMOTE', 'VERY_REMOTE', name='remoteness'), nullable=False),
    sa.Column('sector', sa.Enum('GOVERNMENT', 'CATHOLIC', 'INDEPENDENT', name='schoolsector'), nullable=False),
    sa.Column('foei', sa.Integer(), nullable=True),
    sa.Column('icsea', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('enrolment', sa.Integer(), nullable=True),
    sa.Column('transfer_points', sa.Integer(), nullable=False),
    sa.Column('is_connected_community', sa.Boolean(), nullable=False),
    sa.Column('community_information_url', sa.String(length=150), nullable=True),
    sa.Column('year_from', sa.Integer(), nullable=True),
    sa.Column('year_to', sa.Integer(), nullable=True),
    sa.Column('principal', sa.String(length=100), nullable=True),
    sa.Column('selective', sa.Boolean(), nullable=False),
    sa.Column('boarding', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('NSW_DATASET', 'MANUAL', 'IMPORTED', name='schoolsource'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_updated', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['locality_id'], ['localities.id'], ),
    sa.ForeignKeyConstraint(['school_type_id'], ['school_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_code', name='uq_school_code')
    )
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schools_acara_id'), ['acara_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schools_locality_id'), ['locality_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schools_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_schools_school_code'), ['school_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_schools_school_type_id'), ['school_type_id'], unique=False)

    op.create_table('school_aliases',
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('source', sa.Enum('JOBFEED', 'SCHOOL_FINDER', 'MANUAL', 'HISTORICAL', name='aliassource'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('school_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_aliases_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_aliases_school_id'), ['school_id'], unique=False)

    op.create_table('vacancies',
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('school_name', sa.String(length=255), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('reference_number', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('employment_type', sa.Enum('PERMANENT', 'TEMPORARY', name='employmenttype'), nullable=False),
    sa.Column('full_time', sa.Boolean(), nullable=False),
    sa.Column('position_fraction', sa.Float(), nullable=False),
    sa.Column('number_of_positions', sa.Integer(), nullable=False),
    sa.Column('graduate_position', sa.Boolean(), nullable=False),
    sa.Column('salary_from', sa.Integer(), nullable=True),
    sa.Column('salary_to', sa.Integer(), nullable=True),
    sa.Column('has_relocation_support', sa.Boolean(), nullable=False),
    sa.Column('has_recruitment_bonus', sa.Boolean(), nullable=False),
    sa.Column('recruitment_bonus_amount', sa.Integer(), nullable=False),
    sa.Column('publish_date', sa.Date(), nullable=True),
    sa.Column('closing_date', sa.Date(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description_html', sa.Text(), nullable=True),
    sa.Column('apply_url', sa.String(length=500), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['job_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vacancies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vacancies_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_vacancies_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vacancies_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vacancies_source_id'), ['source_id'], unique=False)

    op.create_table('vacancy_subjects',
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('requirement', sa.Enum('APPROVED', 'WILLING', name='requirementtype'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vacancy_subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vacancy_subjects_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vacancy_subjects_vacancy_id'), ['vacancy_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacancy_subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vacancy_subjects_vacancy_id'))
        batch_op.drop_index(batch_op.f('ix_vacancy_subjects_subject_id'))

    op.drop_table('vacancy_subjects')
    with op.batch_alter_table('vacancies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vacancies_source_id'))
        batch_op.drop_index(batch_op.f('ix_vacancies_school_id'))
        batch_op.drop_index(batch_op.f('ix_vacancies_external_id'))
        batch_op.drop_index(batch_op.f('ix_vacancies_active'))

    op.drop_table('vacancies')
    with op.batch_alter_table('school_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_aliases_school_id'))
        batch_op.drop_index(batch_op.f('ix_school_aliases_name'))

    op.drop_table('school_aliases')
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schools_school_type_id'))
        batch_op.drop_index(batch_op.f('ix_schools_school_code'))
        batch_op.drop_index(batch_op.f('ix_schools_name'))
        batch_op.drop_index(batch_op.f('ix_schools_locality_id'))
        batch_op.drop_index(batch_op.f('ix_schools_acara_id'))

    op.drop_table('schools')
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjects_code'))

    op.drop_table('subjects')
    with op.batch_alter_table('localities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_localities_region_id'))
        batch_op.drop_index(batch_op.f('ix_localities_name'))

    op.drop_table('localities')
    with op.batch_alter_table('school_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_types_name'))
        batch_op.drop_index(batch_op.f('ix_school_types_code'))

    op.drop_table('school_types')
    with op.batch_alter_table('regions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regions_name'))

    op.drop_table('regions')
    op.drop_table('job_sources')
    with op.batch_alter_table('faculties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faculties_code'))

    op.drop_table('faculties')
    # ### end Alembic commands ###
